FROM golang:1.22-alpine

ARG USERNAME=renatus
ARG USER_UID=1000

RUN adduser -u $USER_UID $USERNAME -D && \
    apk add make && go install github.com/spf13/cobra-cli@latest && \
    chown renatus:renatus -R /go
ENV PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

USER $USERNAME
